In [1]:
from transformation_pipeline import transformation_pipeline
import os
import pandas as pd

In [2]:
# Ruta del archivo csv 
FILES_PATH = os.path.join('..','..','data','raw','GeekyMotors')
csv_path = os.path.join(FILES_PATH, 'geeky_motors2.csv')

# Importación del archivo CSV
data = pd.read_csv(csv_path, encoding="latin-1")
#data

## Pipeline

In [3]:
data_transformed = transformation_pipeline(data)
data_transformed

,marca,modelo,anio,carroceria,traccion,combustible,transmision,asientos,color,kilometraje,verificacion,precio
0,tesla,model 3,2018-01-01,sedan,4x4,electrico,automatica,cuero vegano,red multi-coat,44000,93.0,55000
1,audi,q5,2012-01-01,suv,4x2,gasolina,automatica,cuerro,gris,154000,NaN,6500
2,audi,q5,2012-01-01,suv,4x2,gasolina,automatica,cuerro,gris,154000,NaN,6500
3,toyota,corolla se,2019-01-01,sedan,4x2,gasolina,automatica,cuero,azul marino,78000,95.0,17500
4,audi,q5,2012-01-01,suv,4x2,gasolina,automatica,cuerro,gris,154000,NaN,6500
...,...,...,...,...,...,...,...,...,...,...,...,...
4283,nissan,almera,2005-01-01,sedan,4x2,gasolina,automatica,tela,rojo vino,150000,NaN,3500
4284,kia,sportage,2017-01-01,suv,4x2,gasolina,automatica,"tela, oscuros y areas de cuero",negro / gris,96000,NaN,12999
4285,bmw,x5 3.od,2014-01-01,suv,4x4,diesel,automatica,cuero,crema,167000,NaN,18000
4286,jeep,wrangler unlimited,2018-01-01,suv,4x4,gasolina,automatica,tela,beige,78000,NaN,25000
4287,toyota,hilux,2019-01-01,pickup,4x4,diesel,automatica,tela,gris,83000,NaN,34995

In [4]:
data_transformed.to_csv(os.path.join('..','..','data','processed','GeekyMotors','geeky_transformed.csv'))

In [6]:
data_transformed.verificacion.describe()

count    308.000000
mean      94.698052
std        2.328774
min       92.000000
25%       93.000000
50%       95.000000
75%       95.000000
max      100.000000
Name: verificacion, dtype: float64